name: unit-tests
on: [push, pull_request]
jobs:
  OS:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - apt-amd64/ubuntu:devel
          - apt-amd64/ubuntu:latest
          - apt-amd64/ubuntu:rolling
          - apt-i386/ubuntu:rolling
          - apt-amd64/debian:testing
          - dnf-fedora:latest
          - dnf-fedora:rawhide
          - dnf-centos:8
          - alpine-latest
          - alpine-latest@gudev
        include:
          - scenario: alpine-latest@gudev
            env: EXTRA_PACKAGES=libgudev-dev

    timeout-minutes: 30
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Run unit tests
        run: |
          scenario=${{ matrix.scenario }}
          scenario=${scenario%@*}
          script=${scenario%-*}
          release=${scenario#*-}
          ${{ matrix.env }} tests/run-${script} $release
